name: cgmlst-clustering
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8.8
  - cgmlst-dists=0.4.0
  - matplotlib=3.5.1
  - scikit-learn=1.0.2
  - numpy=1.20.2
  - scipy=1.8.0
